local M = {}

function M.apply(palette)
  local groups = {
    -- Telescope
    TelescopeNormal = { link = "NormalFloat" },
    TelescopeBorder = { link = "FloatBorder" },
    TelescopePromptNormal = { fg = "fg", bg = "bg_highlight" },
    TelescopePromptBorder = { fg = "blue", bg = "bg_highlight" },
    TelescopePromptTitle = { fg = "bg", bg = "blue", bold = true },
    TelescopePromptPrefix = { fg = "cyan", bg = "bg_highlight" },
    TelescopePromptCounter = { fg = "muted", bg = "bg_highlight" },
    TelescopeResultsNormal = { fg = "muted", bg = "bg_elevated" },
    TelescopeResultsBorder = { fg = "subtle", bg = "bg_elevated" },
    TelescopeResultsTitle = { fg = "cyan", bold = true },
    TelescopePreviewNormal = { fg = "fg", bg = "bg_elevated" },
    TelescopePreviewBorder = { fg = "subtle", bg = "bg_elevated" },
    TelescopePreviewTitle = { fg = "green", bold = true },
    TelescopeSelection = { fg = "bright_fg", bg = "bg_visual", bold = true },
    TelescopeSelectionCaret = { fg = "orange", bg = "bg_visual", bold = true },
    TelescopeMultiSelection = { fg = "purple", bold = true },
    TelescopeMatching = { fg = "bright_yellow", bold = true },

    -- blink.cmp
    BlinkCmpMenu = { link = "Pmenu" },
    BlinkCmpMenuBorder = { link = "FloatBorder" },
    BlinkCmpMenuSelection = { link = "PmenuSel" },
    BlinkCmpLabel = { fg = "fg" },
    BlinkCmpLabelDeprecated = { fg = "subtle", strikethrough = true },
    BlinkCmpLabelMatch = { fg = "bright_blue", bold = true },
    BlinkCmpLabelDetail = { fg = "muted" },
    BlinkCmpLabelDescription = { fg = "muted", italic = true },
    BlinkCmpKind = { fg = "purple" },
    BlinkCmpSource = { fg = "subtle" },
    BlinkCmpGhostText = { fg = "subtle", italic = true },
    BlinkCmpScrollBarGutter = { bg = "bg_highlight" },
    BlinkCmpScrollBarThumb = { bg = "subtle" },
    BlinkCmpDoc = { link = "NormalFloat" },
    BlinkCmpDocBorder = { link = "FloatBorder" },
    BlinkCmpDocSeparator = { fg = "subtle" },
    BlinkCmpSignatureHelp = { link = "NormalFloat" },
    BlinkCmpSignatureHelpBorder = { link = "FloatBorder" },
    BlinkCmpSignatureHelpActiveParameter = { fg = "bright_yellow", bold = true },

    -- nvim-cmp
    CmpItemAbbr = { fg = "fg" },
    CmpItemAbbrDeprecated = { fg = "subtle", strikethrough = true },
    CmpItemAbbrMatch = { fg = "bright_blue", bold = true },
    CmpItemAbbrMatchFuzzy = { fg = "cyan", bold = true },
    CmpItemMenu = { fg = "muted", italic = true },
    CmpItemKind = { fg = "purple" },
    CmpItemKindText = { fg = "fg" },
    CmpItemKindMethod = { fg = "bright_blue" },
    CmpItemKindFunction = { fg = "blue" },
    CmpItemKindConstructor = { fg = "cyan" },
    CmpItemKindField = { fg = "fg" },
    CmpItemKindVariable = { fg = "fg" },
    CmpItemKindClass = { fg = "cyan" },
    CmpItemKindInterface = { fg = "purple" },
    CmpItemKindModule = { fg = "purple" },
    CmpItemKindProperty = { fg = "fg" },
    CmpItemKindUnit = { fg = "yellow" },
    CmpItemKindValue = { fg = "pink" },
    CmpItemKindEnum = { fg = "cyan" },
    CmpItemKindKeyword = { fg = "red" },
    CmpItemKindSnippet = { fg = "green" },
    CmpItemKindColor = { fg = "pink" },
    CmpItemKindFile = { fg = "blue" },
    CmpItemKindReference = { fg = "cyan" },
    CmpItemKindFolder = { fg = "blue" },
    CmpItemKindEnumMember = { fg = "pink" },
    CmpItemKindConstant = { fg = "pink" },
    CmpItemKindStruct = { fg = "cyan" },
    CmpItemKindEvent = { fg = "orange" },
    CmpItemKindOperator = { fg = "cyan" },
    CmpItemKindTypeParameter = { fg = "bright_cyan" },

    -- Gitsigns
    GitSignsAdd = { fg = "green" },
    GitSignsChange = { fg = "yellow" },
    GitSignsDelete = { fg = "red" },
    GitSignsTopdelete = { fg = "red" },
    GitSignsChangedelete = { fg = "orange" },
    GitSignsUntracked = { fg = "cyan" },
    GitSignsAddNr = { link = "GitSignsAdd" },
    GitSignsChangeNr = { link = "GitSignsChange" },
    GitSignsDeleteNr = { link = "GitSignsDelete" },
    GitSignsAddLn = { link = "DiffAdd" },
    GitSignsChangeLn = { link = "DiffChange" },
    GitSignsDeleteLn = { link = "DiffDelete" },
    GitSignsCurrentLineBlame = { fg = "subtle", italic = true },

    -- Neo-tree
    NeoTreeNormal = { link = "Normal" },
    NeoTreeNormalNC = { link = "NormalNC" },
    NeoTreeFloatNormal = { link = "NormalFloat" },
    NeoTreeFloatBorder = { link = "FloatBorder" },
    NeoTreeFloatTitle = { link = "FloatTitle" },
    NeoTreeCursorLine = { link = "CursorLine" },
    NeoTreeWinSeparator = { link = "WinSeparator" },
    NeoTreeEndOfBuffer = { link = "EndOfBuffer" },
    NeoTreeRootName = { fg = "purple", bold = true },
    NeoTreeDirectoryName = { fg = "blue" },
    NeoTreeDirectoryIcon = { fg = "blue" },
    NeoTreeFileName = { fg = "fg" },
    NeoTreeFileNameOpened = { fg = "bright_fg", bold = true },
    NeoTreeSymbolicLinkTarget = { fg = "cyan", italic = true },
    NeoTreeIndentMarker = { fg = "subtle" },
    NeoTreeDimText = { fg = "muted" },
    NeoTreeGitAdded = { fg = "green" },
    NeoTreeGitConflict = { fg = "bright_red", bold = true },
    NeoTreeGitDeleted = { fg = "red" },
    NeoTreeGitIgnored = { fg = "subtle" },
    NeoTreeGitModified = { fg = "yellow" },
    NeoTreeGitRenamed = { fg = "cyan" },
    NeoTreeGitStaged = { fg = "green" },
    NeoTreeGitUnstaged = { fg = "orange" },
    NeoTreeGitUntracked = { fg = "cyan" },

    -- nvim-tree
    NvimTreeNormal = { link = "Normal" },
    NvimTreeNormalNC = { link = "NormalNC" },
    NvimTreeEndOfBuffer = { link = "EndOfBuffer" },
    NvimTreeWinSeparator = { link = "WinSeparator" },
    NvimTreeCursorLine = { link = "CursorLine" },
    NvimTreeRootFolder = { fg = "purple", bold = true },
    NvimTreeFolderName = { fg = "blue" },
    NvimTreeFolderIcon = { fg = "blue" },
    NvimTreeOpenedFolderName = { fg = "bright_blue", bold = true },
    NvimTreeEmptyFolderName = { fg = "muted" },
    NvimTreeIndentMarker = { fg = "subtle" },
    NvimTreeSpecialFile = { fg = "yellow", underline = true },
    NvimTreeExecFile = { fg = "green", bold = true },
    NvimTreeSymlink = { fg = "cyan", italic = true },
    NvimTreeGitDirty = { fg = "yellow" },
    NvimTreeGitNew = { fg = "green" },
    NvimTreeGitDeleted = { fg = "red" },
    NvimTreeGitIgnored = { fg = "subtle" },
    NvimTreeGitStaged = { fg = "green" },
    NvimTreeGitMerge = { fg = "orange" },
    NvimTreeGitRenamed = { fg = "cyan" },
    NvimTreeModifiedFile = { fg = "yellow" },

    -- Which-key
    WhichKeyNormal = { link = "NormalFloat" },
    WhichKeyBorder = { link = "FloatBorder" },
    WhichKeyTitle = { link = "FloatTitle" },
    WhichKeyGroup = { fg = "purple", bold = true },
    WhichKeyDesc = { fg = "fg" },
    WhichKeySeparator = { fg = "subtle" },
    WhichKeyValue = { fg = "muted" },
    WhichKeyIcon = { fg = "cyan" },

    -- Trouble
    TroubleNormal = { link = "Normal" },
    TroubleNormalNC = { link = "NormalNC" },
    TroubleText = { fg = "fg" },
    TroubleCount = { fg = "purple", bold = true },
    TroubleSource = { fg = "muted" },
    TroubleCode = { fg = "muted" },
    TroublePos = { fg = "subtle" },
    TroubleDirectory = { fg = "blue" },
    TroubleFilename = { fg = "fg", bold = true },
    TroubleIconDirectory = { fg = "blue" },
    TroubleIndent = { fg = "subtle" },
    TroublePreview = { bg = "bg_visual" },
  }

  require("mush.groups.util").apply(palette, groups)
end

return M
