local M = {}

function M.apply(palette, config)
  local groups = {
    Comment = vim.tbl_extend("force", { fg = "muted" }, config.styles.comments),
    Constant = { fg = "pink" },
    String = { fg = "green" },
    Character = { fg = "bright_green" },
    Number = { fg = "yellow" },
    Boolean = { fg = "yellow", bold = true },
    Float = { link = "Number" },
    Identifier = { fg = "fg" },
    Function = vim.tbl_extend("force", { fg = "blue" }, config.styles.functions),
    Statement = vim.tbl_extend("force", { fg = "red" }, config.styles.keywords),
    Conditional = { fg = "red", bold = config.styles.keywords.bold },
    Repeat = { link = "Conditional" },
    Label = { fg = "orange", italic = true },
    Operator = { fg = "cyan" },
    Keyword = vim.tbl_extend("force", { fg = "red" }, config.styles.keywords),
    Exception = { fg = "bright_red", bold = true },
    PreProc = { fg = "orange" },
    Include = { fg = "purple" },
    Define = { fg = "orange", bold = true },
    Macro = { fg = "orange", bold = true },
    PreCondit = { fg = "orange" },
    Type = { fg = "cyan", bold = true },
    StorageClass = { fg = "red" },
    Structure = { link = "Type" },
    Typedef = { link = "Type" },
    Special = { fg = "purple" },
    SpecialChar = { fg = "bright_green" },
    Tag = { fg = "blue" },
    Delimiter = { fg = "muted" },
    SpecialComment = { fg = "cyan", italic = true },
    Debug = { fg = "bright_red" },
    Underlined = { underline = true },
    Ignore = { fg = "subtle" },
    Error = { fg = "bright_red", bold = true },
    Todo = { fg = "bg", bg = "yellow", bold = true },

    DiagnosticError = { fg = "red" },
    DiagnosticWarn = { fg = "yellow" },
    DiagnosticInfo = { fg = "blue" },
    DiagnosticHint = { fg = "cyan" },
    DiagnosticOk = { fg = "green" },
    DiagnosticVirtualTextError = { fg = "red", bg = "bg_elevated" },
    DiagnosticVirtualTextWarn = { fg = "yellow", bg = "bg_elevated" },
    DiagnosticVirtualTextInfo = { fg = "blue", bg = "bg_elevated" },
    DiagnosticVirtualTextHint = { fg = "cyan", bg = "bg_elevated" },
    DiagnosticVirtualTextOk = { fg = "green", bg = "bg_elevated" },
    DiagnosticUnderlineError = { sp = "red", undercurl = true },
    DiagnosticUnderlineWarn = { sp = "yellow", undercurl = true },
    DiagnosticUnderlineInfo = { sp = "blue", undercurl = true },
    DiagnosticUnderlineHint = { sp = "cyan", undercurl = true },
    DiagnosticUnderlineOk = { sp = "green", undercurl = true },
    DiagnosticFloatingError = { link = "DiagnosticError" },
    DiagnosticFloatingWarn = { link = "DiagnosticWarn" },
    DiagnosticFloatingInfo = { link = "DiagnosticInfo" },
    DiagnosticFloatingHint = { link = "DiagnosticHint" },
    DiagnosticFloatingOk = { link = "DiagnosticOk" },
    DiagnosticSignError = { link = "DiagnosticError" },
    DiagnosticSignWarn = { link = "DiagnosticWarn" },
    DiagnosticSignInfo = { link = "DiagnosticInfo" },
    DiagnosticSignHint = { link = "DiagnosticHint" },
    DiagnosticSignOk = { link = "DiagnosticOk" },
    DiagnosticUnnecessary = { fg = "subtle" },
    DiagnosticDeprecated = { strikethrough = true },

    DiffAdd = { fg = "green", bg = "bg_elevated" },
    DiffChange = { fg = "yellow", bg = "bg_elevated" },
    DiffDelete = { fg = "red", bg = "bg_elevated" },
    DiffText = { fg = "bright_yellow", bg = "bg_visual", bold = true },
    Added = { fg = "green" },
    Changed = { fg = "yellow" },
    Removed = { fg = "red" },
    gitcommitAdded = { link = "Added" },
    gitcommitChanged = { link = "Changed" },
    gitcommitRemoved = { link = "Removed" },
  }

  require("mush.groups.util").apply(palette, groups)
end

return M
