local M = {}

function M.apply(palette)
  local groups = {
    ["@variable"] = { fg = "fg" },
    ["@variable.builtin"] = { fg = "purple", italic = true },
    ["@variable.parameter"] = { fg = "fg", italic = true },
    ["@variable.parameter.builtin"] = { fg = "purple", italic = true },
    ["@variable.member"] = { fg = "fg" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = "bright_purple", bold = true },
    ["@constant.macro"] = { link = "Macro" },
    ["@module"] = { fg = "purple" },
    ["@module.builtin"] = { fg = "bright_purple", italic = true },
    ["@label"] = { link = "Label" },
    ["@string"] = { link = "String" },
    ["@string.documentation"] = { fg = "bright_green", italic = true },
    ["@string.regexp"] = { fg = "bright_green" },
    ["@string.escape"] = { fg = "cyan", bold = true },
    ["@string.special"] = { fg = "bright_green" },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@boolean"] = { link = "Boolean" },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = "bright_cyan", bold = true },
    ["@type.definition"] = { link = "Typedef" },
    ["@attribute"] = { fg = "yellow", italic = true },
    ["@attribute.builtin"] = { fg = "bright_yellow", italic = true },
    ["@property"] = { fg = "fg" },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = "bright_blue" },
    ["@function.call"] = { link = "Function" },
    ["@function.macro"] = { link = "Macro" },
    ["@function.method"] = { fg = "bright_blue" },
    ["@function.method.call"] = { fg = "bright_blue" },
    ["@constructor"] = { fg = "cyan", bold = true },
    ["@operator"] = { link = "Operator" },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.coroutine"] = { fg = "purple", bold = true },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.operator"] = { fg = "red" },
    ["@keyword.import"] = { fg = "purple", bold = true },
    ["@keyword.type"] = { link = "Keyword" },
    ["@keyword.modifier"] = { link = "Keyword" },
    ["@keyword.repeat"] = { link = "Repeat" },
    ["@keyword.return"] = { fg = "bright_red", bold = true },
    ["@keyword.debug"] = { fg = "bright_red" },
    ["@keyword.exception"] = { link = "Exception" },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.conditional.ternary"] = { link = "Conditional" },
    ["@keyword.directive"] = { link = "PreProc" },
    ["@keyword.directive.define"] = { link = "Define" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { fg = "muted" },
    ["@punctuation.special"] = { fg = "cyan" },
    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { fg = "muted", italic = true },
    ["@comment.error"] = { fg = "red", bold = true },
    ["@comment.warning"] = { fg = "yellow", bold = true },
    ["@comment.todo"] = { fg = "bg", bg = "yellow", bold = true },
    ["@comment.note"] = { fg = "blue", bold = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.heading"] = { fg = "purple", bold = true },
    ["@markup.quote"] = { fg = "muted", italic = true },
    ["@markup.math"] = { fg = "cyan" },
    ["@markup.link"] = { fg = "blue", underline = true },
    ["@markup.link.label"] = { fg = "purple" },
    ["@markup.link.url"] = { fg = "blue", underline = true },
    ["@markup.raw"] = { fg = "green" },
    ["@markup.list"] = { fg = "orange" },
    ["@diff.plus"] = { link = "Added" },
    ["@diff.minus"] = { link = "Removed" },
    ["@diff.delta"] = { link = "Changed" },
    ["@tag"] = { fg = "blue" },
    ["@tag.builtin"] = { fg = "bright_blue" },
    ["@tag.attribute"] = { fg = "yellow" },
    ["@tag.delimiter"] = { fg = "muted" },
  }

  require("mush.groups.util").apply(palette, groups)
end

return M
